from pathlib import Path


class MTLExporter:
    """
    Export a material library for the generated texture atlas.
    """

    def __init__(
        self,
        output_path: str | Path,
        texture_name: str = "atlas.png",
    ):
        self.output_path = Path(output_path)
        self.texture_name = texture_name

    def export(self) -> None:
        """
        Write the MTL file.
        """

        with self.output_path.open(
            "w",
            encoding="utf-8",
        ) as file:

            file.write("# Generated by RVAtlas\n")
            file.write("\n")

            file.write("newmtl atlas\n")

            file.write("Ka 1.000000 1.000000 1.000000\n")
            file.write("Kd 1.000000 1.000000 1.000000\n")
            file.write("Ks 0.000000 0.000000 0.000000\n")
            file.write("Ns 0.000000\n")
            file.write("d 1.000000\n")
            file.write("illum 2\n")

            file.write(f"map_Kd {self.texture_name}\n")