from pathlib import Path

from rvatlas.models.mesh import Mesh


class OBJExporter:
    """
    Export a Mesh as a Wavefront OBJ file.
    """

    def __init__(
        self,
        mesh: Mesh,
        output_path: str | Path,
        material_library: str = "optimized.mtl",
    ):
        self.mesh = mesh
        self.output_path = Path(output_path)
        self.material_library = material_library

    def export(self) -> None:
        """
        Write the mesh to an OBJ file.
        """

        with self.output_path.open(
            "w",
            encoding="utf-8",
        ) as file:

            self._write_header(file)
            self._write_vertices(file)
            self._write_uvs(file)
            self._write_normals(file)
            self._write_faces(file)

    def _write_header(self, file) -> None:
        """Write the OBJ header."""

        file.write("# Generated by RVAtlas\n")
        file.write("\n")

        file.write(f"mtllib {self.material_library}\n")
        file.write("\n")

        file.write("usemtl atlas\n")
        file.write("\n")

    def _write_vertices(self, file) -> None:
        """Write all vertices."""

        for vertex in self.mesh.vertices:
            file.write(
                f"v {vertex.x:.6f} "
                f"{vertex.y:.6f} "
                f"{vertex.z:.6f}\n"
            )

        file.write("\n")

    def _write_uvs(self, file) -> None:
        """Write all texture coordinates."""

        for uv in self.mesh.uvs:
            file.write(
                f"vt {uv.u:.6f} "
                f"{uv.v:.6f}\n"
            )

        file.write("\n")

    def _write_normals(self, file) -> None:
        """Write all normals."""

        for normal in self.mesh.normals:
            file.write(
                f"vn {normal.x:.6f} "
                f"{normal.y:.6f} "
                f"{normal.z:.6f}\n"
            )

        file.write("\n")

    def _write_faces(self, file) -> None:
        """Write all faces."""

        for face in self.mesh.faces:

            vertices = []

            for face_vertex in face.vertices:

                vertex = face_vertex.vertex_index + 1

                uv = (
                    face_vertex.uv_index + 1
                    if face_vertex.uv_index is not None
                    else ""
                )

                normal = (
                    face_vertex.normal_index + 1
                    if face_vertex.normal_index is not None
                    else ""
                )

                vertices.append(
                    f"{vertex}/{uv}/{normal}"
                )

            file.write(
                f"f {' '.join(vertices)}\n"
            )